export const viewStyles = {
  "--w-rjv-font-family": "Roboto Mono, monospace",
  "--w-rjv-line-color": "var(--contrast-border-base)",
  "--w-rjv-curlybraces-color": "var(--contrast-fg-secondary)",
  "--w-rjv-brackets-color": "var(--contrast-fg-secondary)",
  "--w-rjv-key-string": "var(--contrast-fg-primary)",
  "--w-rjv-info-color": "var(--contrast-fg-secondary)",
  "--w-rjv-type-string-color": "var(--tag-green-icon)",
  "--w-rjv-quotes-string-color": "var(--tag-green-icon)",
  "--w-rjv-type-boolean-color": "var(--tag-orange-icon)",
  "--w-rjv-type-int-color": "var(--tag-orange-icon)",
  "--w-rjv-type-float-color": "var(--tag-orange-icon)",
  "--w-rjv-type-bigint-color": "var(--tag-orange-icon)",
  "--w-rjv-key-number": "var(--contrast-fg-secondary)",
  "--w-rjv-arrow-color": "var(--contrast-fg-secondary)",
  "--w-rjv-copied-color": "var(--contrast-fg-secondary)",
  "--w-rjv-copied-success-color": "var(--contrast-fg-primary)",
  "--w-rjv-colon-color": "var(--contrast-fg-primary)",
  "--w-rjv-ellipsis-color": "var(--contrast-fg-secondary)",
}
